version: 2
updates:
  - package-ecosystem: "uv" # See documentation for possible values
    versioning-strategy: increase-if-necessary
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
